config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end
  
  get 'charges/downgrade'
  resources :charges, only: [:new, :create, :downgrade]
  
  
  root 'welcome#index'


end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :wiki
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  
  after_initialize :user_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
         
  enum role: [:standard, :premium, :admin]
  
  def user_role
    self.role ||= :standard
  end

  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  before_save :set_private
  
  def collaborator_for(user)
    collaborators.find_by(user: user)
  end
  
  private
  
  def set_private
    self.private ||= false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    include Pundit
    protect_from_forgery with: :exception
    
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    
    private 
    
    def user_not_authorized
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to(request.referrer || root_path)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    include Amount
    
    def new
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key] }",
            description: "Premium Membership - #{current_user.email}",
            amount: Amount.default
        }
    end
    
    def create
        # Creates a Stripe Customer object, for associating with the charge
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )
        
        # Where the charges take place
        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: Amount.default,
            description: "Premium Membership - #{current_user.email}",
            currency: 'usd'
        )
        
        current_user.update_attribute(:role, :premium)
        
        flash[:notice] = "Thanks for your payment, #{current_user.email}.  You now have access to private Wikis."
        redirect_to root_path(current_user)
        
        # Displays CardErrors when something goes wrong
        rescue Stripe::CardError => e
            flash[:alert] = e.message
            redirect_to new_charge_path
    end
    
    def downgrade
        current_user.standard!
        current_user.wikis.update_all(private: false)
        flash[:notice] = "You are now a standard Wiki user.  You only have access to public Wikis."
        redirect_to root_path(current_user)
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki
  
  def index
    @users = User.all
  end
  
  def create
    @collaborator = @wiki.collaborators.new(:user_id => params[:user_id])
    
    if @collaborator.save
      flash[:notice] = "Collaborator was added."
    else
      flash.now[:alert] = "There was an error adding the collaborator.  Please try again."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end
  
  def destroy
    @collaborator = @wiki.collaborators.find(params[:id])
    
    if @collaborator.destroy
      flash[:notice] = "\"#{@collaborator.user.email}\" was removed as a Collaborator successfully."
    else
      flash.now[:alert] = "There was an error deleting this collaborator."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end
  
  private 
  
  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    skip_before_action :authenticate_user!
    
    def index
    end

end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    def index
        @wikis = policy_scope(Wiki)
    end
    
    def show
        @wiki = Wiki.find(params[:id])
    end
    
    def new
        @wiki = Wiki.new
        authorize @wiki
    end
    
    def create
        @wiki = current_user.wikis.new(wiki_params)
        authorize @wiki
        
        
        if @wiki.save
            flash[:notice] = "Wiki was saved."
            redirect_to @wiki
        else
            flash.now[:alert] = "There was an error saving the wiki.  Please try again."
            render :new
        end
    end
    
    def edit
        @wiki = Wiki.find(params[:id])
        authorize @wiki
    end
    
    def update
        @wiki = Wiki.find(params[:id])
        @wiki.assign_attributes(wiki_params)
        authorize @wiki
        
        if @wiki.save
            flash[:notice] = "Wiki was saved."
            redirect_to @wiki
        else
            flash.now[:alert] = "There was an error saving the wiki.  Please try again."
            render :edit
        end
    end
    
    def destroy
        @wiki = Wiki.find(params[:id])
        authorize @wiki
        
        if @wiki.destroy
            flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
            redirect_to wikis_path
        else
            flash.now[:alert] = "There was an error deleting this wiki."
            render :show
        end
    end
    
    private 
    
    def wiki_params
        params.require(:wiki).permit(:title, :body, :private)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>

    <h4>Become a Premium Plan User!</h4>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
    data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>"
    data-description="<%= @stripe_btn_data[:description] %>" ></script>
    
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/destroy.html.erb
<h1>Collaborators#destroy</h1>
<p>Find me in app/views/collaborators/destroy.html.erb</p>

app/views/collaborators/index.html.erb
<div class="collaborator-heading">
    <h1>Add or Remove User as Collaborator</h1>
</div>
<div class="container">
    <table class="table table-striped">
        <% @users.each do |user| %>
            <tr>
                <td><h5><%= user.email %></h5></td>
                <% if @wiki.users.include?(user) %>
                    <td>
                        <% collaborator = @wiki.collaborator_for(user) %>
                        <%= link_to "Remove Collaborator", wiki_collaborator_path(@wiki, collaborator), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to remove this collaborator?'} %>
                    </td>
                <% else %>
                    <td><%= link_to "Add Collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: 'btn btn-success' %></td>
                <% end %>
            </tr>
        <% end %>
    </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <div class="navbar-brand">
        <%= link_to "Home", root_path %> |
        <%= link_to "Wikis", wikis_path %>
      </div>
      <ul class="navbar-nav pull-right">
        <% if user_signed_in? %>
          <li>Signed in as: <strong><%= current_user.email %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - 
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
          <% end %>
      </ul>
    </div>
    
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <br>
    <%= yield %>
  </div>
</nav>

</body>
</html>

app/views/welcome/_form.html.erb
<% if user_signed_in? && current_user.standard? %>
    <div class="row">
        <div class="col-md-6">
            <h4>Create public wikis!</h4>
        </div>
        <div class="col-md-6">
            <h4>Create private wikis!</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <p><%= link_to "Public Wikis", new_wiki_path, class: 'btn btn-primary' %></p>
        </div>
        <div class="col-md-6">
            <p><%= link_to "Premium Plan", new_charge_path, class: 'btn btn-success' %></p>
        </div>
    </div>
<% elsif user_signed_in? && current_user.premium? %>
    <div class="private">
        <div class="row">
            <div class="col-md-12">
                <h4>Create wikis!</h4>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <p><%= link_to "Create Wiki", new_wiki_path, class: 'btn btn-success' %></p>
            </div>
        </div>
    </div>
<% else %>
    <div class="row">
        <div class="col-md-6">
            <h4>Create public wikis!</h4>
        </div>
        <div class="col-md-6">
            <h4>Create private wikis!</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <p><%= link_to "Public Wikis", new_wiki_path, class: 'btn btn-primary' %></p>
        </div>
        <div class="col-md-6">
            <p><%= link_to "Premium Plan", new_charge_path, class: 'btn btn-success' %></p>
        </div>
    </div>
<% end %>

app/views/welcome/index.html.erb
<br>
<div class="page-header">
    <h2>Blocipedia: Social, Markdown Wikis</h2>
</div>

<div class="jumbotron">
    <p>Create and share Markdown Wikis</p>
    <p>
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success' %>
    </p>
</div>

<%= render partial: 'form' %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki Title" %>
    </div>
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 12, class: 'form-control', placeholder: "Enter Wiki Body" %>
    </div>
    <% if current_user.admin? || (current_user.premium? && current_user == @wiki.user) %>
        <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
            <% end %>
        </div>
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
            <%= link_to "Edit Collaborators", wiki_collaborators_path(@wiki), class: 'btn btn-primary' %>
        </div>
    <% else %>
        <div class="form-group">
            <%= f.submit "Save", class: 'btn btn-success' %>
        </div>
    <% end %>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
    <div class="col-md-12">
        <%= render partial: 'form' %>
    </div>
</div>

app/views/wikis/index.html.erb
<div class="row">
    <div class="col-md-8">
        <h1>Wikis</h1>    
    </div>
    <div class="col-md-4">
        <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-primary' %>
    </div>
</div>

<% @wikis.each do |wiki| %>
    <p><%= link_to wiki.title, wiki %></p>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
    <div class="col-md-12">
         <%= render partial: 'form' %>
    </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
    <div class="col-md-8">
        <p><%= markdown(@wiki.body) %></p>
    </div>
    <div class="col-md-4">
        <% if policy(@wiki).update? %>
            <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
            <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
        <% end %>
    </div>
</div>